Sprint 13 add-controllers
RuslanYapparov/java-shareit pull request #1
Opened 2023-06-14 06:56 UTC by RuslanYapparov

Создал "скелет" будущего приложения с распределением логики по слоям, использованием CRUD- и прочих интерфейсов, а также объектов RestCommand и RestView, реализовал функционал, касающийся пользователей и вещей, требуемый в соответствии с техническим заданием проектной работы 13-го спринта. Хотелось, но не успел написать юнит-тесты.

2023-06-15 10:02 UTC, sergeymamonov requested changes
Не нужно отлавливать NullPointerException, см. объяснение в замечании.
Проверьте везде модификатор доступа. Потому что где-то вы используете @Value, а где-то нет.

Не стремитесь везде делать ТОЛЬКО через интерфейс и везде выделять абстракции и использовать наследование. Здесь тонкая грань использования этих вещей, чтобы не скатиться в код, который будет сильно запутан.

2023-06-15 10:02 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +        User user = User.builder()
А почему в одном методе через билдер, а во втором через сеттеры? Лучше делать все единообразно.

2023-06-15 19:42 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/common/CrudApi.java
> +    V save(@Positive long userId, @Valid C commandObject) throws BadRequestHeaderException;
Я думал, это полезно, чтобы подсказать другим программистам, что метод может выбрасывать такое исключение. Когда проходил теорию по обработке исключений, где-то в подсознании отложилось, что это хороший тон и привычка. 
Убрал указания о выбрасываемых исключениях в интерфейсах.

2023-06-15 19:42 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/item/dao/impl/InMemoryItemDaoImpl.java
> +            itemIsAvailable = item.getIsAvailable();
Почему-то на первых этапах получил NPE, когда пытался получить значение поля available. Тогда решил, что нужно обернуть в проверку, хотя знал (потому что Вы раньше говорили), что это плохой знак. С тех пор логики приросло и теперь, когда убрал этот try-catch, все работает нормально. Действительно, в этой проверке нет никакой необходимости.

2023-06-15 19:42 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/item/dao/impl/InMemoryItemDaoImpl.java
> +        Item savedItem = this.getById(itemId);
Пробежался по коду, убрал использование ключевого слова this во всех местах кроме конструкторов

2023-06-15 19:42 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/item/dao/impl/InMemoryItemDaoImpl.java
> +                .description(itemDescription.equals(ShareItConstants.NOT_ASSIGNED) ?
Хоть ранее в логике эти поля и проверялись на null при сохранении, но такая проверка на соответствие намного более логична, и почему я сам не додумался... Исправил во всех местах, где проверяется соответствие, стало лучше, потому что ушли дополнительные проверки на null

2023-06-15 19:42 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/item/dto/ItemRestCommand.java
> +    float rent;
Наверное, на данном этапе обучения некрасиво с моей стороны делать такие упущения. Типичная детская ошибка ctrl-c ctrl-v. 
Добавил модификаторы во всех классах, где пропустил.

2023-06-15 19:44 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/user/address/dto/UserAddressRestCommand.java
> +public class UserAddressRestCommand implements Receivable<UserAddressRestCommand> {
Убрал интерфейс Receivable, логику поведения данного интерфейса для объектов restCommand перенес в класс-компонент RestCommandObjectValidator

2023-06-16 06:06 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        itemService.checkUserExisting(userId);
Проверку существования пользователя перенес в сервисы, но валидацию и присвоение дефолтных значений сущностям остваил на этапе маппинга объектов-команд в объекты сервисного слоя (то есть, наверное, ближе к презентационному слою. Решил, что лучше сначала проверить и потом замапить, чем наоборот)

2023-06-16 06:09 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +        User user = User.builder()
Изменил способ создания объектов restView для использования билдера. В прошлом проекте пришлось использовать NoArgsConstructor для юнит-тестов, иначе jackson ругался на отсутствие дефолтного creator. Пока тестов нет и в обычном режиме все работает нормально.

2023-06-16 06:24 UTC, RuslanYapparov commented
Спасибо за ревью, важные замечания и полезные советы! За модификаторы доступа обидно, ведь столько раз смотрел на эти классы и так и не заметил, что их не хватает. Постарался отработать по всем комментариям, оптимизировал код, убрал несколько интерфейсов и излишнее наследование, но оставил интерфейсы и дефолтную имплементацию для CRUD-операций со всеми объектами, кроме пользователей.

2023-06-16 18:43 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/common/CrudApi.java
> +    V save(@Positive long userId, @Valid C commandObject) throws BadRequestHeaderException;
Нужно понимать разницу между обрабатываемыми и не обрабатываемыми исключениями. И что с ними делать..

2023-06-16 18:50 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/common/crud/default_implementations/CrudServiceImpl.java
> +    public T save(long userId, T object) throws ObjectAlreadyExistsException {
А здесь почему осталось throws ObjectAlreadyExistsException? И ниже в методах

2023-06-16 18:50 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/common/crud/default_implementations/InMemoryCrudDaoImpl.java
> +    public T save(T object) throws ObjectAlreadyExistsException {
В этом классе аналогично. Удалить указание необрабатываемого исключения из описания методов.

2023-06-16 18:50 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/dao/impl/InMemoryItemDaoImpl.java
> +            itemIsAvailable = item.getIsAvailable();
Если вы получили NPE, то нужно было не прикрывать его, чтобы оно было незаметно, а разобраться почему оно сгенерировалось. Почему делать проверку на null хорошая практика - потому что система может состоять из разных микросервисов, а это могут быть разные команды, то есть ошибка будет не в вашем коде. Или пользователь что-то не заполнил, и вы в бэке получили null в каком-то поле. То есть проверка на null это способ обезопасить себя от невалидных данных. Поэтому если вы сомневаетесь или не доверяете каким-то данным, то сделайте проверку на null через if. try/catch - это способ отлавливания ошибок, но не не проверки данных.

2023-06-22 07:16 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/user/address/dto/UserAddressRestCommand.java
> +public class UserAddressRestCommand {
Ранее получал ошибку от jackson об отсутствии дефолтного creator, которым выступал конструктор без аргументов, поэтому сделал классы-команды изменяемыми. Но сейчас попробовал сделать иммутабельными с помощью "Value" и все работает. Это немного искажает мое понимание того, как оно все работает, вроде ничего же не поменялось. В любом случае, все классы, касающиеся сущностей сделал иммутабельными и однообразными (с использованием аннотаций "Value" и "Builder").

2023-06-22 07:16 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/common/crud/default_implementations/InMemoryCrudDaoImpl.java
> +    public T save(T object) throws ObjectAlreadyExistsException {
Убрал все указания необрабатываемых исключений после определений методов всех классов (до этого были убраны только в интерфейсах)

2023-06-22 07:16 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/common/crud/default_implementations/CrudServiceImpl.java
> +    public T save(long userId, T object) throws ObjectAlreadyExistsException {
Убрал все указания необрабатываемых исключений после определений методов всех классов (до этого были убраны только в интерфейсах)

2023-06-22 07:21 UTC, merged