Sprint 14 add-bookings
RuslanYapparov/java-shareit pull request #2
Opened 2023-06-29 14:38 UTC by RuslanYapparov

Включена работа с репозиториями ORM-фреймворка, добавлены функциональности бронирования и оставления комментариев, а также необходимые проверки при их работе, предусмотренные техническим заданием проектной работы 14-го спринта. Включены дополнения от себя - дополнительные поля с предыдущего спринта, а также функционал записывания даты и времени сохранения и последнего изменения сущностей. Не нашел способа организации работы hibernate с неизменяемыми объектами, поэтому для сохранения иммутабельности объектов слоев сервиса и внешнего представления добавил изменяемые классы-entity для всех сущностей слоя репозиториев. Это вызвало дополнительные "накладные расходы", связанные с мэппингом объектов. Тестирование не реализовано.

2023-06-30 19:43 UTC, sergeymamonov requested changes
В мапперах можно проще делать через source, и указывать нужное поле в ресурсе.

2023-06-30 19:43 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            if (userId != bookingEntity.getItem().getUserId()) {
В данном случае условие двух if можно объединить через &&

2023-06-30 19:43 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/common/DomainObjectValidator.java
> +    default Set<Long> checkSetFieldWithLongs(Set<Long> value) {
Метод где-то используется?

2023-06-30 19:43 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    @Mapping(target = "isAvailable", expression = "java(itemRestCommand.getAvailable())")
Можно проще @Mapping(target = "isAvailable", source = "available")

2023-07-01 11:39 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            if (userId != bookingEntity.getItem().getUserId()) {
Изначально использовал логическое И (почему-то казалось, что нужно обязательно проверить оба "множителя" логического умножения) и узнал, что это антипаттерн, проверяемый spotbugs. После изменения на && ошибка повторилась, поэтому решил использовать вложенное ветвление, при этом понимая, что это некрасиво и нехорошо. 
Наверное, перед запуском чека spotbugs с двумя амперсандами не пересобрал программу, поэтому ошибка и повторилась. Теперь, когда внес изменения в соответствии с Вашим комментарием все проверяется без ошибок.

2023-07-01 11:39 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/common/DomainObjectValidator.java
> +    default Set<Long> checkSetFieldWithLongs(Set<Long> value) {
После изменения логики с полями-коллекциями данный метод перестал использоваться и был "благополучно" забыт. Неловко вышло, метод удалил.

2023-07-01 11:40 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    @Mapping(target = "isAvailable", expression = "java(itemRestCommand.getAvailable())")
Немного пересмотрел нэйминг полей с примитивными типами (и одним типом-оберткой Boolean). В результате интерфейс ItemMapper стал более оптимизированным, но пострадало следование правилам наименования булевых полей (убрал использование is в названии). 
Способ мэппинга с указанием целевого значения и источника применил к конвертации полей userId -> ownerId, так действительно более просто и лаконично, чем использование выражения.

2023-07-02 19:10 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            if (userId != bookingEntity.getItem().getUserId()) {
Что используете статический анализатор кода это отлично.

2023-07-02 19:15 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    @Mapping(target = "isAvailable", expression = "java(itemRestCommand.getAvailable())")
Вообще стараются поля из класса в класс называть одинаково, чтобы не нужно было в мапперах указывать что на что маппить. is часто не указывают, lombok добавит is в имена геттера и сеттера автоматически.

2023-07-02 19:19 UTC, sergeymamonov approved these changes

2023-07-02 19:19 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    @Mapping(target = "bookerId", expression = "java(bookingEntity.getUserId())")
а не пробовали здесь @Mapping(target = "bookerId", source = "userId")? Думаю, что так проще и будет тоже работать.

2023-07-05 05:14 UTC, merged