Sprint 15 add-item-requests
RuslanYapparov/java-shareit pull request #4
Opened 2023-07-12 14:02 UTC by RuslanYapparov

Реализовал требуемую функциональность запросов на вещи и покрыл код учебного приложения тестами. Функциональность запросов максимально протестирована, для остальных сущностей написаны тесты, указанные в задании к проектной работе.

2023-07-12 22:50 UTC, sergeymamonov requested changes
Название метода checkUserAndObjectExistingAndReturnEntityFromDb - здесь что-то не то. Либо с названием перемудрили, либо метод делает много всего. Метод должен делать строго одну задачу. И эта задача должна быть выражена в названии. Если вы легко придумываете название методу, то скорее всего метод хорошо спроектирован (делает одну задачу). А если название методу сложно подобрать, то скорее всего метод не очень хорошо спроектирован.

Сколько раз в проекте встречается написанный метод checkPaginationParameters? Проверка пагинации из класса в класс разная? Лучше выделить отдельный класс валидатор с методом и использовать этот метод из других классов.

2023-07-12 22:50 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>          switch (state) {
state можно сделать перечислением.

2023-07-12 22:50 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/common/CrudServiceImpl.java
>      public V save(long userId, C commandObject) {       // Переопределяется в сервисе любой сущности, связанной с User
Если вы пишите, что переопределяется в сервисе любой сущности, зачем тогда эта базовая реализация? Она где-то используется? Если нет, то метод можно сделать абстрактным.

2023-07-13 20:27 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private void checkUserIdForNullValue(long userId, String operation) {
Создал класс MethodParameterValidator со статическими вызовами методов проверки, перенес эту валидацию в сервисный слой.

2023-07-13 20:27 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Pageable page = PageRequest.of(from > 0 ? from / size : 0, size, sortByBookingStart);
На ранних этапах скопировал из теории темы и не задумался над предшествующей валидацией. Пробежался по коду и исправил кажется во всех местах на from / size

2023-07-13 20:34 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/common/CrudServiceImpl.java
>      public V save(long userId, C commandObject) {       // Переопределяется в сервисе любой сущности, связанной с User
Сделал CrudSeriveImpl абстрактным классом и объявил метод сохранения абстрактным. Подумав над механизмом абстракции, решил, что для других методов проще оставить как есть, так как их использование и переопределение встречается не для всех сущностей. Убрал комментарии, вводящие в заблуждение.

2023-07-14 08:38 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>          switch (state) {
Изначально так и сделал, но потом показалось, что выглядит лучше с обработкой в switch строкового значения. В любом случае, переписал для использования перечисления.

2023-07-14 08:39 UTC, RuslanYapparov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
Воспользовался данным советом. Согласен, что так выглядит лаконичней.

2023-07-14 08:46 UTC, RuslanYapparov commented
Спасибо за полезные советы и указания! 
Отрефакторил и переименовал метод checkUserAndObjectExistingAndReturnEntityFromDb - после наименований методов репозиториев и тестов, его название и действия не вызвало настороженности, хотя видно, что оно нарушает принципы проектирования. 
Сделал выводы по валидации и использованию однообразных методов check в разных классах, но валидацию аннотациями пока решил не переносить в сервисы из-за необходимости переписывания тестов.

2023-07-14 14:21 UTC, sergeymamonov approved these changes

2023-07-14 14:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/common/MethodParameterValidator.java
> +
Для информации есть аннотация https://projectlombok.org/features/experimental/UtilityClass

2023-07-14 14:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +//    @Mapping(target = "booker", expression = "java(toBooker(booking))")
Не оставляйте закомментированный код в проекте.

2023-07-14 14:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>          switch (state) {
Перечисление более надежный вариант. Когда литерал в тексте, можно случайно удалить букву из него и все скомпилируется в большинстве случаев. С перечислением сразу идея подсветит.

2023-07-16 15:55 UTC, merged