Sprint 16 add-docker
RuslanYapparov/java-shareit pull request #5
Opened 2023-07-21 07:32 UTC by RuslanYapparov

В соответствии с техническим заданием проектной работы 16-го спринта разделил приложение на 2 микросервиса, внедрив предварительную валидацию (все проверки, для проведения которых нет необходмости подгружать данные из базы) поступающих данных в сервисе gateway. Таким образом, перенес и созданный на прошлом спринте утилитарный класс MethodParameterValidator, переименовав его в EndpointObjectsValidator. Написал тесты для нового сервиса с покрытием 97%. В контейнерах реализовал возможность подключения для отладки и проверил ее работоспособность.

2023-07-21 21:28 UTC, sergeymamonov requested changes
Если вы используете And в названии метода - то это повод задуматься, верно ли скомпонован метод или верно ли я подбираю название.

2023-07-21 21:28 UTC, sergeymamonov commented on gateway/src/test/java/ru/practicum/shareit_gateway/booking/Booker.java
> +public class Booker {
А почему в пакете с тестами классы? Классы (не тесты) точно нужно удалить.

2023-07-21 21:28 UTC, sergeymamonov commented on gateway/src/test/java/ru/practicum/shareit_gateway/booking/BookingControllerTest.java
> +    public void save_whenGetCorrectParameters_thenReturnCorrectRestViewObject() throws Exception {
Этот тест практически дублирует аналогичный тест в модуле основного сервиса. Тут нужно выбрать какие тесты вы пишите. Если модульные, то значит основной сервис нужно замокировать в тесте, то есть использовать не сам основной сервис, а его заглушку. Либо, если вы пишите интеграционные тесты, то тест в модуле основного сервиса не нужен и его нужно удалить. Но не настаиваю на этом изменении, можете и так оставить.

2023-07-21 21:28 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit_server/booking/dto/BookingRestCommand.java
>      long itemId;
Я бы на эти поля тоже навесил аннотацию @JsonProperty

2023-07-21 21:28 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit_server/booking/BookingServiceImpl.java
>          BookingEntity bookingEntity = checkUserConsistencyAndReturnEntity(userId, bookingId);
checkUserConsistencyAndReturnEntity - лучше давать более простые названия. Я бы назвал findBooking, например. Entity сбивает, говорит, что метод может возвращать разные сущности, а если посмотреть код, то только бронирования.

2023-07-23 09:18 UTC, RuslanYapparov commented on gateway/src/test/java/ru/practicum/shareit_gateway/booking/BookingControllerTest.java
> +    public void save_whenGetCorrectParameters_thenReturnCorrectRestViewObject() throws Exception {
Кажется, только теперь ко мне пришло окончательное понимание устройства интеграционных и  модульных тестов. Понимаю необходимость включения интеграционного тестирования в этом модуле, но учитывая открытие следующего спринта и то, что Вы не настаиваете, оставлю так - если будет время, попробую сделать позже.

2023-07-23 10:04 UTC, RuslanYapparov commented on server/src/main/java/ru/practicum/shareit_server/booking/BookingServiceImpl.java
>          BookingEntity bookingEntity = checkUserConsistencyAndReturnEntity(userId, bookingId);
Думал, что простое название метода не информативно и нужно добавить в названии побольше описания его действий. Объединив несколько Ваших советов решил попробовать назвать метод используя if в названии: getBookingEntityIfCorrectBooker() и getItemEntityForBookingIfCorrectParameters(). Допускаются ли такие названия или лучше все-таки максимально упростить до findBooking() или findBookingItem()

2023-07-23 10:04 UTC, RuslanYapparov commented on server/src/main/java/ru/practicum/shareit_server/booking/dto/BookingRestCommand.java
>      long itemId;
Добавил аннотацию @JsonProperty во все restCommand классы, где она отсутствовала.

2023-07-23 10:04 UTC, RuslanYapparov commented on gateway/src/test/java/ru/practicum/shareit_gateway/booking/Booker.java
> +public class Booker {
Классы использовались в логике сериализации/десериализации в тестах, но не использовались в основной логике модуля, поэтому решил, что их можно включить только для тестов. Перенес классы в пакеты dto. 
Остался вопрос по поводу отдельного тестировочного класса Foo, который я ввел в прошлом спринте для тестирования общих логических классов в папке common основного сервиса. Допускается ли использование таких тестовых классов-сущностей?

2023-07-23 10:04 UTC, RuslanYapparov commented on gateway/src/main/java/ru/practicum/shareit_gateway/exception/InternalLogicException.java
> +public class InternalLogicException extends RuntimeException {
В рамках данного модуля данное исключение выкидывалось только в тестах в методах-заглушках, потому что название исключения мне показалось подходящим. В основном модуле оно использовалось 2 раза в switch-case с перечислениями для обработки ситуации с отсутствием обработки какого-то значения enum.
Убрал данное исключение и его обработку из логики данного модуля и заменил в тестах.

2023-07-23 10:04 UTC, RuslanYapparov commented on gateway/src/main/java/ru/practicum/shareit_gateway/booking/BookingController.java
> +			@PositiveOrZero @RequestHeader(value = "X-Sharer-User-Id", defaultValue = "0") long userId,
Единственный плюс самописных проверок был в отправке чуть более информативных сообщений о неправильных параметрах, чем поступающих по умолчанию от validator'а. Согласен, что этим плюсом легко можно пренебречь для лаконичности кода. 
Убрал утилитарный класс EndpointObjectsValidator и оставил только валидацию аннотациями

2023-07-23 10:04 UTC, RuslanYapparov commented on gateway/Dockerfile
> +#ENV TZ=Europe/Samara
В учебной беседе узнал, что без этой переменной не пройти тесты postman локально, но в CI тесты уже не пройдут, если ее оставить. Подумал, что dockerfile не является файлом кода в прямом смысле и для удобства можно просто закомментировать элемент. 
Убрал переменную окружению из варианта для CI.

2023-07-24 19:07 UTC, sergeymamonov commented on gateway/src/test/java/ru/practicum/shareit_gateway/booking/Booker.java
> +public class Booker {
Нет, такие классы создавать не нужно. Если для теста вам нужен какой-то реальный объект, значит нужно его создать на основе существующего класса.

2023-07-24 19:08 UTC, sergeymamonov approved these changes

2023-07-25 06:46 UTC, merged